### ISSUE TITLE
Re-default isPermalink

### ISSUE THREAD

**Issue by tobiassjosten** [lib16/rss-builder-php#1]
The [RSS specification](https://validator.w3.org/feed/docs/rss2.html) states:

>isPermaLink is optional, its default value is true. If its value is false, the guid may not be assumed to be a url, or a url to anything in particular.

The behaviour in this library is the opposite – `isPermalink` defaults to *false*. Further, when `isPermalink` is *false* (either by argument or default) it's not being printed in the final RSS. This makes it impossible to use non-permalink values for guid.

If you want I can roll a PR for this? In fact, I could roll one that maintains backwards compatibility (still defaulting to false but actually printing it) and one for future versions that also changes the default value to true.

**Comment by hoffmann-oss** [comment]
Thank you, thank you, thank you, the default value now is null.
